# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f5a3bafe8258843fb540618c4977046abae3ce4e267063d958d7090d262f546f799122e83a2608539b7db3d54a6772aed95219a77afe990453dd068865c962d
  facebook_app_id: 643856862452060
  facebook_app_secret: e851c499593cbf0b048569aec038b996
  twitter_app_id: UoCA94G7sREnPybooOcdvfSkR
  twitter_app_secret: abXFhXCrU3PvDMaEbc9bQrEG9qGPL91laN478SSxvhYv059wb9
test:
  secret_key_base: fb6dee10d929e355cc5989ec4f56543091e84fc8a80def33dd2fd946840d5f9c6af8457aec3b9dfe28571b0b3aee6215efc11a3e597022f36ec6984afce8b88c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  twitter_app_id: <%= ENV["TWITTER_APP_ID"] %>
  twitter_app_secret: <%= ENV["TWITTER_APP_SECRET"] %>
